# Generated by Django 2.0.12 on 2019-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('attr_rating', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('attr_tag', models.IntegerField(choices=[(0, 'Wystawa'), (1, 'Centrum Nauki'), (2, 'Park'), (3, 'Park Rozrywki'), (4, 'Park Linowy'), (5, 'Park Miniatur'), (6, 'Ogród'), (7, 'Centrum Zabaw'), (8, 'Zoo'), (9, 'Plac zabaw'), (10, 'Wodny Plac zabaw'), (11, 'AguaPark'), (12, 'Tor sanezckowy'), (13, 'Farma'), (14, 'Sport'), (15, 'Event'), (16, 'Nietypowe'), (17, 'Przyjazne niepełnosprawnym'), (18, 'Dostępne po angielsku')], max_length=18, unique=True)),
                ('attr_foto1', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr_foto2', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr_foto3', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr_people', models.IntegerField(choices=[(0, '1'), (1, '2-4'), (2, '5-8'), (3, 'więcej')])),
                ('attr_price', models.CharField(max_length=24)),
                ('attr_duration', models.IntegerField(choices=[(0, 'do 30 min'), (1, 'do 2 godzin'), (2, 'kilka godzin'), (3, 'cały dzień'), (4, 'nieokreślony')])),
                ('attr_www', models.CharField(max_length=32)),
                ('attr1_foto', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr1_title', models.CharField(blank=True, max_length=32, null=True)),
                ('attr1_info', models.CharField(blank=True, max_length=150, null=True)),
                ('attr2_foto', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr2_title', models.CharField(blank=True, max_length=32, null=True)),
                ('attr2_info', models.CharField(blank=True, max_length=150, null=True)),
                ('attr3_foto', models.ImageField(blank=True, null=True, upload_to='media/attr/')),
                ('attr3_title', models.CharField(blank=True, max_length=32, null=True)),
                ('attr3_info', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Atrakcja',
                'verbose_name_plural': 'Atrakcje',
            },
        ),
    ]
