# Generated by Django 2.0.12 on 2019-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anim_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('zakres', models.IntegerField(choices=[(0, 'moja miejsowość'), (1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie'), (17, 'cały kraj')])),
                ('anim_rating', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('anim_people', models.IntegerField(choices=[(0, '1'), (1, '2-4'), (2, '5-8'), (3, 'więcej')])),
                ('anim_price', models.CharField(max_length=24)),
                ('anim_duration', models.IntegerField(choices=[(0, 'do 30 min'), (1, 'do 2 godzin'), (2, 'kilka godzin'), (3, 'cały dzień'), (4, 'nieokreślony')])),
                ('anim_www', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Animacja',
                'verbose_name_plural': 'Animacje',
            },
        ),
        migrations.CreateModel(
            name='AnimTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anim_tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AttrTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='media/general')),
            ],
        ),
        migrations.CreateModel(
            name='Wabik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wabik_foto', models.ImageField(blank=True, null=True, upload_to='media/wabik/')),
                ('wabik_title', models.CharField(blank=True, max_length=32, null=True)),
                ('wabik_info', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr1_foto',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr1_info',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr1_title',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr2_foto',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr2_info',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr2_title',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr3_foto',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr3_info',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr3_title',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr_foto1',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr_foto2',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr_foto3',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attr_tag',
        ),
        migrations.AddField(
            model_name='animation',
            name='anim_foto',
            field=models.ManyToManyField(to='datrakcje.GeneralFoto'),
        ),
        migrations.AddField(
            model_name='animation',
            name='anim_tags',
            field=models.ManyToManyField(to='datrakcje.AnimTag'),
        ),
        migrations.AddField(
            model_name='animation',
            name='anim_wabik',
            field=models.ManyToManyField(to='datrakcje.Wabik'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attr_foto',
            field=models.ManyToManyField(to='datrakcje.GeneralFoto'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attr_tags',
            field=models.ManyToManyField(to='datrakcje.AttrTag'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attr_wabik',
            field=models.ManyToManyField(to='datrakcje.Wabik'),
        ),
    ]
