# Generated by Django 2.0.12 on 2019-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attr_tag',
            field=models.IntegerField(choices=[(0, 'Wystawa'), (1, 'Centrum Nauki'), (2, 'Park'), (3, 'Park Rozrywki'), (4, 'Park Linowy'), (5, 'Park Miniatur'), (6, 'Ogród'), (7, 'Centrum Zabaw'), (8, 'Zoo'), (9, 'Plac zabaw'), (10, 'Wodny Plac zabaw'), (11, 'AguaPark'), (12, 'Tor sanezckowy'), (13, 'Farma'), (14, 'Sport'), (15, 'Event'), (16, 'Nietypowe'), (17, 'Przyjazne niepełnosprawnym'), (18, 'Dostępne po angielsku')]),
        ),
    ]
