# Generated by Django 2.0.12 on 2019-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0002_auto_20190908_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anim_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('zakres', models.IntegerField(choices=[(0, 'moja miejsowość'), (1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie'), (17, 'cały kraj')])),
                ('anim_rating', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('anim_tag', models.IntegerField(choices=[(0, 'Wata cukrowa'), (1, 'Balony z helem'), (2, 'Żywe maskotki'), (3, 'Tematyczne'), (4, 'Teatr'), (5, 'Wypożyczalnia'), (6, 'Balonowe Zoo'), (7, 'Konkursy'), (8, 'Kreatywne zabawy'), (9, 'Świat baniek'), (10, 'Zabawy ruchowe'), (11, 'Sport'), (12, 'Zagadki'), (13, 'Gry'), (14, 'Piniata'), (15, 'Nietypowe'), (16, 'Przyjazne niepełnosprawnym'), (17, 'Dostępne po angielsku')])),
                ('anim_foto1', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim_foto2', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim_foto3', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim_people', models.IntegerField(choices=[(0, '1'), (1, '2-4'), (2, '5-8'), (3, 'więcej')])),
                ('anim_price', models.CharField(max_length=24)),
                ('anim_duration', models.IntegerField(choices=[(0, 'do 30 min'), (1, 'do 2 godzin'), (2, 'kilka godzin'), (3, 'cały dzień'), (4, 'nieokreślony')])),
                ('anim_www', models.CharField(max_length=32)),
                ('anim1_foto', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim1_title', models.CharField(blank=True, max_length=32, null=True)),
                ('anim2_foto', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim2_title', models.CharField(blank=True, max_length=32, null=True)),
                ('anim2_info', models.CharField(blank=True, max_length=150, null=True)),
                ('anim3_foto', models.ImageField(blank=True, null=True, upload_to='media/anim/')),
                ('anim3_title', models.CharField(blank=True, max_length=32, null=True)),
                ('anim1_info', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Animacja',
                'verbose_name_plural': 'Animacje',
            },
        ),
    ]
