# Generated by Django 2.0.12 on 2019-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0002_auto_20190914_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfoto',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=32, null=True),
        ),
    ]
