# Generated by Django 2.0.12 on 2019-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0003_generalfoto_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='anim_www',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attr_www',
            field=models.CharField(max_length=128),
        ),
    ]
