# Generated by Django 2.0.12 on 2019-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0004_auto_20190914_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='anim_people',
            field=models.IntegerField(choices=[(0, '1'), (1, '2-4'), (2, '5-8'), (3, 'więcej niż 8')]),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attr_people',
            field=models.IntegerField(choices=[(0, '1'), (1, '2-4'), (2, '5-8'), (3, 'więcej niż 8')]),
        ),
    ]
