# Generated by Django 2.0.12 on 2019-09-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datrakcje', '0005_auto_20190914_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='anim_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
